import {ClayIconSpriteContext} from '@clayui/icon';

import {TokenStoreProvider} from './theme/tokenStore';
import {Workbench} from './workbench/Workbench';

/**
 * The spritemap is generated by `pnpm icons` into `public/`, so it keeps a stable, unhashed URL.
 * `BASE_URL` rather than a bare '/' so the app still resolves its icons when served from a
 * subpath — a GitHub Pages deploy, for instance.
 */
const spritemap = `${import.meta.env.BASE_URL}icons.svg`;

export function App() {
	return (
		<ClayIconSpriteContext.Provider value={spritemap}>
			<TokenStoreProvider>
				<Workbench />
			</TokenStoreProvider>
		</ClayIconSpriteContext.Provider>
	);
}
